import playGame from "./players";

describe("Winner of the game", () => {
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "r",
            "d",
            "d",
            "r",
            "r",
            "r",
            "l",
            "l",
            "l",
            "d",
            "d",
            "d",
            "l",
            "d",
            "d",
            "d",
            "d",
            "r",
        ];
        const player2 = [
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "d",
            "d",
            "l",
            "l",
            "u",
            "u",
            "r",
            "u",
            "l",
        ];
        expect(playGame(player1, player2)).toBe("player2");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "d",
            "d",
            "r",
            "r",
            "r",
            "u",
            "r",
            "d",
            "d",
            "d",
            "d",
            "l",
            "d",
            "r",
            "r",
            "r",
            "u",
            "u",
        ];
        const player2 = [
            "l",
            "l",
            "l",
            "u",
            "u",
            "l",
            "u",
            "u",
            "u",
            "r",
            "r",
            "u",
            "l",
            "l",
            "l",
            "l",
            "u",
            "r",
        ];
        expect(playGame(player1, player2)).toBe("draw");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "d",
            "d",
            "d",
            "d",
            "d",
            "d",
            "d",
            "d",
            "r",
            "r",
            "r",
            "r",
            "r",
            "u",
            "u",
            "u",
            "u",
            "u",
        ];
        const player2 = [
            "u",
            "u",
            "u",
            "u",
            "u",
            "u",
            "u",
            "u",
            "l",
            "l",
            "l",
            "l",
            "l",
            "d",
            "d",
            "d",
            "d",
            "d",
        ];
        expect(playGame(player1, player2)).toBe("draw");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "d",
            "d",
            "d",
            "d",
            "d",
            "d",
            "d",
            "d",
            "r",
            "r",
            "r",
            "r",
            "r",
            "u",
            "u",
            "u",
            "u",
            "u",
        ];
        const player2 = [
            "u",
            "u",
            "u",
            "u",
            "u",
            "u",
            "u",
            "u",
            "l",
            "l",
            "l",
            "l",
            "l",
            "d",
            "d",
            "d",
            "r",
            "d",
        ];
        expect(playGame(player1, player2)).toBe("draw");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "d",
            "d",
            "d",
            "d",
            "u",
            "u",
            "r",
            "d",
            "d",
            "d",
            "d",
            "l",
            "d",
            "r",
            "r",
            "r",
            "u",
            "u",
        ];
        const player2 = [
            "l",
            "l",
            "l",
            "l",
            "r",
            "l",
            "u",
            "u",
            "u",
            "r",
            "r",
            "u",
            "l",
            "l",
            "l",
            "l",
            "u",
            "r",
        ];
        expect(playGame(player1, player2)).toBe("draw");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "r",
            "d",
            "d",
            "r",
            "r",
            "r",
            "d",
            "r",
            "r",
            "d",
            "d",
            "d",
            "l",
            "d",
            "d",
            "d",
            "d",
            "r",
        ];
        const player2 = [
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "d",
            "d",
            "l",
            "l",
            "u",
            "u",
            "r",
            "u",
            "l",
        ];
        expect(playGame(player1, player2)).toBe("player2");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "r",
            "d",
            "d",
            "r",
            "r",
            "r",
            "d",
            "r",
            "r",
            "d",
            "d",
            "d",
            "r",
            "u",
            "u",
            "u",
            "d",
            "r",
        ];
        const player2 = [
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "u",
            "u",
            "u",
            "u",
            "u",
            "l",
            "l",
            "u",
            "u",
            "r",
            "u",
            "l",
        ];
        expect(playGame(player1, player2)).toBe("player1");
    });
    test("Should return winner of the game or draw", () => {
        const player1 = [
            "r",
            "d",
            "r",
            "r",
            "u",
            "r",
            "u",
            "u",
            "u",
            "d",
            "d",
            "d",
            "r",
            "u",
            "u",
            "u",
            "d",
            "r",
        ];
        const player2 = [
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "u",
            "l",
            "l",
            "d",
            "d",
            "l",
            "l",
            "u",
            "u",
            "r",
            "u",
            "l",
        ];
        expect(playGame(player1, player2)).toBe("player2");
    });
});
